# SEO settings
title: "chaonan99"
title2: "'s blog" # default: ""
description: "Personal blog for Haonan Chen~"
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://chaonan99.github.io/ # site url
# baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/chaonan99/
disqus_shortname: "chaonan99"
# twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge
host: 0.0.0.0
port: 4000

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Haonan Chen"
  job      : "PhD, UNC-CH"
  bio      : "I am fond of pigs. Dogs look up to us. Cats look down on us. Pigs treat us as equals. -- Winston Churchill"
  thumb    : /images/author.jpg
  email    : chenhaonan1995@gmail.com
  url      : http://chaonan99.github.io
  github   : http://github.com/chaonan99
  # twitter  : http://twitter.com/HeiswayiNrird
  # facebook : https://www.facebook.com/profile.php?id=100011500520270
  # linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "zh_CN"
# twitter_card: "summary_large_image"
# twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
